version: 2

updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - frontend

  - package-ecosystem: pip
    directory: /services/common
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend

  - package-ecosystem: pip
    directory: /services/risk-engine
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci