#!/usr/bin/env python3
"""Generate database/neon_full_reset.sql — wipe, rebuild, and re-seed in one file.

Why this exists
---------------
`neon_setup.sql` (the other generated file) is a ONE-TIME snapshot: its core seed
rows are plain INSERTs, so running it twice against the same database aborts with

    ERROR: duplicate key value violates unique constraint "assets_pkey"

This generator wraps the same schema + migrations + seed in a RESET prologue, so
the resulting file is **idempotent end to end**: it drops everything it is about
to create, then recreates it. Run it as many times as you like; run it on a fresh
Neon database; run it to recover from a partial run.

How it is built
---------------
Nothing here is hand-transcribed. The SCHEMAS and TABLES sections are the real
`database/init.sql` and `database/migrations/*.sql` files, and the SEED section is
reused verbatim from `generate_neon_setup.seed_section()`. So this file cannot
drift away from the migrations the application actually applies at boot.

Run:  python database/generate_full_reset.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

# Reused rather than reimplemented, so the two generated files cannot disagree.
from generate_neon_setup import CONNECTION_STRING, seed_section  # noqa: E402

DATABASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = DATABASE_DIR.parent
INIT_SQL = DATABASE_DIR / "init.sql"
MIGRATIONS_DIR = DATABASE_DIR / "migrations"
OUT_SQL = DATABASE_DIR / "neon_full_reset.sql"

# Named schemas, in the order database/init.sql creates them.
SCHEMAS = ["auth", "asset", "vuln", "control", "risk", "investment", "gov"]

# Objects created outside the named schemas by migrations 009 and 012. The
# `public` schema itself is never dropped: Neon keeps its own objects there
# (neon_timestamptz and friends), and removing it would break the project.
PUBLIC_TABLES = ["public.data_sources", "public.alert_rules"]

EXPECTED_COUNTS = [
    ("auth.users", 3),
    ("asset.assets", 12),
    ("asset.asset_dependencies", 18),
    ("control.security_controls", 10),
    ("control.asset_controls", 14),
    ("vuln.vulnerabilities", 15),
    ("risk.risk_calculations", 12),
    ("risk.risk_snapshots", 25),
    ("gov.agencies", 3),
    ("gov.sector_profiles", 3),
    ("gov.vendors", 3),
    ("gov.asset_vendors", 8),
    ("public.data_sources", 7),
]

RULE = "-- " + "=" * 70


def banner(part: str, title: str, subtitle: str = "") -> list[str]:
    out = ["", RULE, f"-- {part} · {title}"]
    if subtitle:
        out.append(f"-- {subtitle}")
    out.append(RULE)
    out.append("")
    return out


def header() -> list[str]:
    return [
        "-- CyberRisk Quantifier — NeonDB FULL RESET + SETUP (one file, re-runnable)",
        "-- Generated by database/generate_full_reset.py — do not hand-edit.",
        "--",
        "-- HOW TO USE",
        "--   Neon Console -> SQL Editor -> select your database -> paste this",
        "--   entire file -> Run. The file wipes and rebuilds itself, so it is",
        "--   safe to run repeatedly and safe on an empty database.",
        "--",
        "--   You do NOT need to create a database by hand: Neon creates one named",
        "--   `neondb` when you create a project, and the connection string Neon",
        "--   gives you already points at it. If you want a differently named",
        "--   database instead, uncomment the CREATE DATABASE line in PART 1 and",
        "--   change the database name at the end of your connection string.",
        "--",
        "-- TARGET DATABASE (placeholder — set the real URL as DATABASE_URL)",
        f"--   {CONNECTION_STRING}",
        "--",
        "-- WHAT THIS DOES",
        "--   PART 1  Drop every schema and table this project owns",
        "--   PART 2  Create the seven schemas",
        "--   PART 3  Apply migrations 001-012 (tables, indexes, functions, rules)",
        "--   PART 4  Seed 3 demo users, 12 assets, 10 controls, 15 vulnerabilities,",
        "--           14 asset-control links, 18 dependencies, 12 risk calculations,",
        "--           25 weekly snapshots, 3 agencies, 3 sector profiles, 3 vendors,",
        "--           8 vendor links, 1 cyber-drill exercise, 2 early warnings,",
        "--           7 ingestion data sources and the alert rule set",
        "--   PART 5  Print row counts plus an audit-chain integrity check",
        "",
        "-- IDEMPOTENCY",
        "--   PART 1 is what makes this safe to re-run. Every statement in the",
        "--   file is either IF EXISTS, IF NOT EXISTS, ON CONFLICT, or follows the",
        "--   reset, so a second run produces the same result as the first rather",
        "--   than a duplicate-key error.",
        "",
        "-- DEMO LOGINS (password for all three: Scro@2026!)",
        "--   scro_regulator / regulator@scro.gov.in  -> CISO",
        "--   scro_banker    / banker@scro.gov.in     -> ANALYST",
        "--   scro_auditor   / auditor@scro.gov.in    -> ANALYST",
        "",
    ]


def reset_section() -> list[str]:
    out = banner("PART 1", "RESET — drop everything this project owns")
    out.append("-- Safe on a database that has never been used: every DROP is IF EXISTS.")
    out.append("-- CASCADE also removes dependent indexes, views and triggers.")
    out.append("--")
    out.append("-- Uncomment only if you want a database other than Neon's default:")
    out.append("-- CREATE DATABASE cyberrisk;")
    out.append("--")
    for schema in SCHEMAS:
        out.append(f"DROP SCHEMA IF EXISTS {schema} CASCADE;")
    out.append("")
    for table in PUBLIC_TABLES:
        out.append(f"DROP TABLE IF EXISTS {table} CASCADE;")
    out.append("")
    return out


def schema_section() -> list[str]:
    out = banner("PART 2", "SCHEMAS", "verbatim from database/init.sql")
    out.append(INIT_SQL.read_text(encoding="utf-8").rstrip())
    out.append("")
    return out


def table_section() -> list[str]:
    out = banner("PART 3", "TABLES, INDEXES, FUNCTIONS, RULES", "migrations 001-012, in order")
    for migration in sorted(MIGRATIONS_DIR.glob("*.sql")):
        out.append("")
        out.append("-- " + "-" * 68)
        out.append(f"-- MIGRATION · {migration.name}")
        out.append("-- " + "-" * 68)
        out.append("")
        out.append(migration.read_text(encoding="utf-8").rstrip())
        out.append("")
    return out


def seed_part() -> list[str]:
    out = banner("PART 4", "SEED DATA", "verbatim from database/generate_neon_setup.py")
    out.extend(seed_section())
    out.append("")
    return out


def verify_section() -> list[str]:
    out = banner("PART 5", "VERIFICATION", "expected counts come from database/neon_quickstart.sql")
    union = " UNION ALL ".join(
        f"SELECT '{name}' AS table_name, COUNT(*) AS rows FROM {name}" for name, _ in EXPECTED_COUNTS
    )
    out.append("-- Row counts. Compare against the expected values in the comment above.")
    out.append(f"{union}")
    out.append("ORDER BY table_name;")
    out.append("")
    out.append("-- Total objects created, per schema.")
    out.append("SELECT table_schema, COUNT(*) AS tables")
    out.append("FROM information_schema.tables")
    out.append(f"WHERE table_schema IN ({', '.join(repr(s) for s in SCHEMAS)})")
    out.append("GROUP BY table_schema ORDER BY table_schema;")
    out.append("")
    out.append("-- Audit hash-chain integrity. broken_links MUST be 0.")
    out.append("SELECT COUNT(*) AS broken_links")
    out.append("FROM risk.audit_entries AS c")
    out.append("WHERE c.prev_hash IS NOT NULL")
    out.append("  AND NOT EXISTS (SELECT 1 FROM risk.audit_entries p WHERE p.data_hash = c.prev_hash);")
    out.append("")
    out.append("-- Demo users, with their roles. Expect 3 rows.")
    out.append("SELECT username, email, role, is_active FROM auth.users ORDER BY role DESC, username;")
    out.append("")
    return out


def main() -> int:
    parts: list[list[str]] = [
        header(),
        reset_section(),
        schema_section(),
        table_section(),
        seed_part(),
        verify_section(),
    ]
    output = "\n".join("\n".join(part) for part in parts)

    if output.startswith("\ufeff"):
        output = output.lstrip("\ufeff")
    OUT_SQL.write_text(output, encoding="utf-8", newline="\n")

    print(f"Wrote {OUT_SQL}")
    print(f"  {len(output):,} chars, {output.count(chr(10))} lines")
    print(f"  drops {len(SCHEMAS)} schemas + {len(PUBLIC_TABLES)} public tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())