-- CyberRisk Quantifier — NeonDB FULL SETUP (schema + all seed data)
-- Generated by database/generate_neon_setup.py
-- Paste the ENTIRE file into the NeonDB SQL editor and run once.
--
-- Target database:
--   postgresql://neondb_owner:npg_v90bkyJEYxjn@ep-solitary-base-b3t4dq9g-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
--
-- What this does:
--   1. Creates schemas: auth, asset, vuln, control, risk, investment, gov
--   2. Applies migrations 001–012 (all tables, indexes, functions, alert rules)
--   3. Seeds: 3 demo users, 12 assets, 10 controls, 15 vulnerabilities,
--      14 asset-control links, 18 dependencies, risk calculations for every
--      asset, 25 weekly historical snapshots, 3 agencies, 3 sector profiles,
--      3 vendors, 8 vendor links, 1 cyber-drill exercise, 2 early warnings,
--      and 7 ingestion data sources.
--
-- Intended for a ONE-TIME run on a fresh (empty) database. Schemas use
-- IF NOT EXISTS but core seed inserts (assets, vulnerabilities, risk
-- calculations, snapshots) are plain INSERTs, so do not re-run on an
-- already-seeded database.
--
-- Demo logins (password for all three: Scro@2026!):
--   scro_regulator / regulator@scro.gov.in  -> CISO
--   scro_banker    / banker@scro.gov.in     -> ANALYST
--   scro_auditor   / auditor@scro.gov.in    -> ANALYST


-- ======================================================================
-- PART 1 · SCHEMA INITIALIZATION (init.sql)
-- ======================================================================

-- CyberRisk Quantifier — Schema Initialization
-- Run against NeonDB: creates all schemas

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS asset;
CREATE SCHEMA IF NOT EXISTS vuln;
CREATE SCHEMA IF NOT EXISTS control;
CREATE SCHEMA IF NOT EXISTS risk;
CREATE SCHEMA IF NOT EXISTS investment;

-- Allow Python services to access all schemas
-- (NeonDB connection uses public schema search_path + explicit schema prefixes)


-- ======================================================================
-- MIGRATION · 001_create_auth_tables.sql
-- ======================================================================

-- Migration 001: Auth tables

CREATE TABLE IF NOT EXISTS auth.users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username        VARCHAR(50) UNIQUE NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    full_name       VARCHAR(255),
    role            VARCHAR(20) NOT NULL DEFAULT 'ANALYST',
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS auth.audit_logs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID REFERENCES auth.users(id),
    action          VARCHAR(100) NOT NULL,
    resource_type   VARCHAR(50),
    resource_id     VARCHAR(50),
    details         TEXT,
    ip_address      VARCHAR(45),
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON auth.audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON auth.audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON auth.audit_logs(created_at DESC);

-- Seed the three SCRO demo users.
--   scro_regulator -> CISO  (regulatory oversight / national access)
--   scro_banker     -> ANALYST (sector operations)
--   scro_auditor    -> ANALYST (national audit & assurance)
-- Password for all three accounts is: Scro@2026!
INSERT INTO auth.users (username, email, password_hash, full_name, role)
VALUES ('scro_regulator', 'regulator@scro.gov.in', '$2b$10$iiW3oECAzxyM1Mh674EVle..tTrqD4Rv141BmywmZgmjvFITKi8oW', 'Regulatory Oversight', 'CISO')
ON CONFLICT (username) DO UPDATE SET
  email = EXCLUDED.email,
  password_hash = EXCLUDED.password_hash,
  full_name = EXCLUDED.full_name,
  role = EXCLUDED.role,
  is_active = true;

INSERT INTO auth.users (username, email, password_hash, full_name, role)
VALUES ('scro_banker', 'banker@scro.gov.in', '$2b$10$iiW3oECAzxyM1Mh674EVle..tTrqD4Rv141BmywmZgmjvFITKi8oW', 'Banking Sector Officer', 'ANALYST')
ON CONFLICT (username) DO UPDATE SET
  email = EXCLUDED.email,
  password_hash = EXCLUDED.password_hash,
  full_name = EXCLUDED.full_name,
  role = EXCLUDED.role,
  is_active = true;

INSERT INTO auth.users (username, email, password_hash, full_name, role)
VALUES ('scro_auditor', 'auditor@scro.gov.in', '$2b$10$iiW3oECAzxyM1Mh674EVle..tTrqD4Rv141BmywmZgmjvFITKi8oW', 'National Security Auditor', 'ANALYST')
ON CONFLICT (username) DO UPDATE SET
  email = EXCLUDED.email,
  password_hash = EXCLUDED.password_hash,
  full_name = EXCLUDED.full_name,
  role = EXCLUDED.role,
  is_active = true;

-- Only the three SCRO demo users may log in — any legacy user is disabled.
UPDATE auth.users SET is_active = false
WHERE username IN ('admin', 'ciso', 'analyst');


-- ======================================================================
-- MIGRATION · 002_create_asset_tables.sql
-- ======================================================================

-- Migration 002: Asset tables

CREATE TABLE IF NOT EXISTS asset.assets (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                    VARCHAR(255) NOT NULL,
    asset_type              VARCHAR(50) NOT NULL,
    environment             VARCHAR(20) DEFAULT 'PRODUCTION',
    owner                   VARCHAR(255),
    department              VARCHAR(100),
    ip_address              INET,
    mac_address             VARCHAR(17),
    operating_system        VARCHAR(100),
    business_value_inr      DECIMAL(15,2) NOT NULL DEFAULT 0,
    replacement_cost_inr    DECIMAL(15,2) DEFAULT 0,
    internet_exposed        BOOLEAN DEFAULT false,
    criticality_score       INTEGER DEFAULT 50,
    data_sensitivity        VARCHAR(20) DEFAULT 'INTERNAL',
    annual_revenue_impact   DECIMAL(15,2) DEFAULT 0,
    metadata                JSONB,
    created_at              TIMESTAMP DEFAULT NOW(),
    updated_at              TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS asset.asset_dependencies (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id        UUID REFERENCES asset.assets(id) ON DELETE CASCADE,
    depends_on_id   UUID REFERENCES asset.assets(id) ON DELETE CASCADE,
    dependency_type VARCHAR(30) NOT NULL,
    criticality     INTEGER DEFAULT 50,
    created_at      TIMESTAMP DEFAULT NOW(),
    UNIQUE(asset_id, depends_on_id)
);

CREATE INDEX IF NOT EXISTS idx_assets_criticality ON asset.assets(criticality_score DESC);
CREATE INDEX IF NOT EXISTS idx_assets_type ON asset.assets(asset_type);
CREATE INDEX IF NOT EXISTS idx_assets_environment ON asset.assets(environment);
CREATE INDEX IF NOT EXISTS idx_assets_department ON asset.assets(department);
CREATE INDEX IF NOT EXISTS idx_assets_exposed ON asset.assets(internet_exposed) WHERE internet_exposed = true;
CREATE INDEX IF NOT EXISTS idx_asset_deps_asset ON asset.asset_dependencies(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_deps_depends ON asset.asset_dependencies(depends_on_id);


-- ======================================================================
-- MIGRATION · 003_create_vuln_tables.sql
-- ======================================================================

-- Migration 003: Vulnerability tables

CREATE TABLE IF NOT EXISTS vuln.vulnerabilities (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cve_id          VARCHAR(20),
    cwe_id          VARCHAR(20),
    title           VARCHAR(500) NOT NULL,
    description     TEXT,
    cvss_score      DECIMAL(3,1) NOT NULL,
    severity        VARCHAR(10) NOT NULL,
    exploitability  DECIMAL(3,1) DEFAULT 0,
    affected_asset  UUID,
    internet_exposed BOOLEAN DEFAULT false,
    status          VARCHAR(20) DEFAULT 'OPEN',
    remediation     TEXT,
    discovered_at   TIMESTAMP DEFAULT NOW(),
    remediated_at   TIMESTAMP,
    source          VARCHAR(50),
    metadata        JSONB,
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vuln_severity ON vuln.vulnerabilities(severity);
CREATE INDEX IF NOT EXISTS idx_vuln_status ON vuln.vulnerabilities(status);
CREATE INDEX IF NOT EXISTS idx_vuln_asset ON vuln.vulnerabilities(affected_asset);
CREATE INDEX IF NOT EXISTS idx_vuln_cvss ON vuln.vulnerabilities(cvss_score DESC);
CREATE INDEX IF NOT EXISTS idx_vuln_cve ON vuln.vulnerabilities(cve_id);
CREATE INDEX IF NOT EXISTS idx_vuln_source ON vuln.vulnerabilities(source);
CREATE INDEX IF NOT EXISTS idx_vuln_discovered ON vuln.vulnerabilities(discovered_at DESC);


-- ======================================================================
-- MIGRATION · 004_create_control_tables.sql
-- ======================================================================

-- Migration 004: Security control tables

CREATE TABLE IF NOT EXISTS control.security_controls (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                    VARCHAR(255) NOT NULL,
    control_type            VARCHAR(30) NOT NULL,
    description             TEXT,
    implementation_cost_inr DECIMAL(12,2) NOT NULL DEFAULT 0,
    annual_maintenance_inr  DECIMAL(12,2) DEFAULT 0,
    max_risk_reduction      DECIMAL(5,4) DEFAULT 0,
    implementation_time_days INTEGER DEFAULT 30,
    maturity_levels         INTEGER DEFAULT 3,
    created_at              TIMESTAMP DEFAULT NOW(),
    updated_at              TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS control.asset_controls (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id            UUID,
    control_id          UUID REFERENCES control.security_controls(id) ON DELETE CASCADE,
    status              VARCHAR(20) DEFAULT 'PLANNED',
    coverage_score      DECIMAL(5,4) DEFAULT 0,
    effectiveness_score DECIMAL(5,4) DEFAULT 0,
    maturity_level      INTEGER DEFAULT 1,
    implemented_at      TIMESTAMP,
    last_verified_at    TIMESTAMP,
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW(),
    UNIQUE(asset_id, control_id)
);

CREATE INDEX IF NOT EXISTS idx_controls_type ON control.security_controls(control_type);
CREATE INDEX IF NOT EXISTS idx_asset_controls_asset ON control.asset_controls(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_controls_status ON control.asset_controls(status);


-- ======================================================================
-- MIGRATION · 005_create_risk_tables.sql
-- ======================================================================

-- Migration 005: Risk tables

CREATE TABLE IF NOT EXISTS risk.risk_calculations (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id                UUID,
    risk_score              DECIMAL(5,2) NOT NULL,
    probability             DECIMAL(5,4) NOT NULL,
    financial_impact_inr    DECIMAL(15,2) NOT NULL,
    expected_annual_loss    DECIMAL(15,2) NOT NULL,
    risk_category           VARCHAR(20) NOT NULL,
    risk_factors            JSONB,
    control_reduction       DECIMAL(5,4) DEFAULT 0,
    residual_risk           DECIMAL(15,2) DEFAULT 0,
    calculated_at           TIMESTAMP DEFAULT NOW(),
    version                 INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS risk.risk_snapshots (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id                UUID,
    risk_score              DECIMAL(5,2),
    expected_annual_loss    DECIMAL(15,2),
    total_controls_active   INTEGER,
    total_vulns_open        INTEGER,
    snapshot_date           DATE NOT NULL,
    created_at              TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS risk.risk_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type      VARCHAR(50) NOT NULL,
    source_asset    UUID,
    details         JSONB,
    risk_before     DECIMAL(5,2),
    risk_after      DECIMAL(5,2),
    eal_before      DECIMAL(15,2),
    eal_after       DECIMAL(15,2),
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_calc_asset ON risk.risk_calculations(asset_id);
CREATE INDEX IF NOT EXISTS idx_risk_calc_score ON risk.risk_calculations(risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_risk_calc_category ON risk.risk_calculations(risk_category);
CREATE INDEX IF NOT EXISTS idx_risk_calc_date ON risk.risk_calculations(calculated_at DESC);
CREATE INDEX IF NOT EXISTS idx_risk_snapshots_date ON risk.risk_snapshots(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_risk_snapshots_asset ON risk.risk_snapshots(asset_id);
CREATE INDEX IF NOT EXISTS idx_risk_events_date ON risk.risk_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_risk_events_type ON risk.risk_events(event_type);


-- ======================================================================
-- MIGRATION · 006_create_investment_tables.sql
-- ======================================================================

-- Migration 006: Investment tables

CREATE TABLE IF NOT EXISTS investment.investment_plans (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                        VARCHAR(255) NOT NULL,
    total_budget_inr            DECIMAL(15,2) NOT NULL,
    expected_risk_reduction     DECIMAL(5,4) DEFAULT 0,
    expected_eal_reduction_inr  DECIMAL(15,2) DEFAULT 0,
    rosi                        DECIMAL(8,4) DEFAULT 0,
    status                      VARCHAR(20) DEFAULT 'DRAFT',
    created_by                  UUID,
    created_at                  TIMESTAMP DEFAULT NOW(),
    updated_at                  TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS investment.investment_items (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id             UUID REFERENCES investment.investment_plans(id) ON DELETE CASCADE,
    control_id          UUID,
    allocation_inr      DECIMAL(12,2) NOT NULL,
    risk_reduction      DECIMAL(5,4) DEFAULT 0,
    expected_rosi       DECIMAL(8,4) DEFAULT 0,
    priority            INTEGER DEFAULT 0,
    implementation_start DATE,
    implementation_end   DATE,
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_investment_plan_status ON investment.investment_plans(status);
CREATE INDEX IF NOT EXISTS idx_investment_plan_created ON investment.investment_plans(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_investment_items_plan ON investment.investment_items(plan_id);


-- ======================================================================
-- MIGRATION · 007_create_audit_tables.sql
-- ======================================================================

-- Migration 007: Risk decision audit hash-chain

CREATE TABLE IF NOT EXISTS risk.audit_entries (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chain_position  INTEGER NOT NULL UNIQUE,
    prev_hash       VARCHAR(64) NOT NULL,
    data_hash       VARCHAR(64) NOT NULL,
    action          VARCHAR(100) NOT NULL,
    actor           VARCHAR(255),
    asset_id        UUID,
    details         JSONB,
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_chain_position ON risk.audit_entries(chain_position DESC);
CREATE INDEX IF NOT EXISTS idx_audit_created ON risk.audit_entries(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_asset ON risk.audit_entries(asset_id);


-- ======================================================================
-- MIGRATION · 008_create_sovereignty_tables.sql
-- ======================================================================

-- Migration 008: Sovereign Cyber-Risk Observatory governance schema
-- Creates the gov schema, adds governance dimensions to asset.assets,
-- and establishes the third-party risk (TPRM) tables.

-- ─── gov schema ───────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS gov;

-- Agencies / public organs / enterprises under observation
CREATE TABLE IF NOT EXISTS gov.agencies (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name             VARCHAR(255) NOT NULL UNIQUE,
    agency_type      VARCHAR(30) NOT NULL DEFAULT 'PUBLIC',
                     -- PUBLIC, REGULATOR, GOVT, PSU, PRIVATE
    sector           VARCHAR(50),
    region           VARCHAR(50),
    parent_agency_id UUID REFERENCES gov.agencies(id),
    classification   VARCHAR(20) DEFAULT 'CONFIDENTIAL',
    created_at       TIMESTAMP DEFAULT NOW()
);

-- Sector profiles: regulator ownership + SRI weight + thresholds
CREATE TABLE IF NOT EXISTS gov.sector_profiles (
    sector                 VARCHAR(50) PRIMARY KEY,
    sector_name            VARCHAR(255) NOT NULL,
    regulator              VARCHAR(255),
    threshold_critical_mln DECIMAL(12,2) DEFAULT 0,
    weight                 NUMERIC(5,4) DEFAULT 1.0,
    created_at             TIMESTAMP DEFAULT NOW()
);

-- National cyber exercises / drills (history)
CREATE TABLE IF NOT EXISTS gov.exercises (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                  VARCHAR(255) NOT NULL,
    scenario_key          VARCHAR(100) NOT NULL,
                          -- WORM, RANSOMWARE, SUPPLY_CHAIN, DDOS
    impact_scope          VARCHAR(30) NOT NULL DEFAULT 'NATIONAL',
                          -- SECTOR, REGION, AGENCY, NATIONAL
    sector                VARCHAR(50),
    region                VARCHAR(50),
    baseline_eal          DECIMAL(15,2),
    simulated_eal         DECIMAL(15,2),
    eal_reduction         DECIMAL(15,2),
    eal_reduction_percent DECIMAL(6,2),
    status                VARCHAR(20) DEFAULT 'COMPLETED',
                          -- COMPLETED, RUNNING, SCHEDULED
    executed_by           UUID,
    executed_at           TIMESTAMP DEFAULT NOW()
);

-- Early warnings / escalations
CREATE TABLE IF NOT EXISTS gov.early_warnings (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    warning_type    VARCHAR(50) NOT NULL,
                    -- EAL_SPIKE, SECTOR_CRITICAL, VULN_BREACH, VENDOR_RISK
    target_type     VARCHAR(30) NOT NULL,
                    -- SECTOR, REGION, AGENCY, ASSET, VENDOR
    target_id       VARCHAR(100),
    severity        VARCHAR(10) NOT NULL,
                    -- CRITICAL, HIGH, MEDIUM, LOW
    title           VARCHAR(500),
    description     TEXT,
    threshold_value DECIMAL(15,2),
    current_value   DECIMAL(15,2),
    status          VARCHAR(20) DEFAULT 'OPEN',
                    -- OPEN, ESCALATED, RESOLVED
    created_at      TIMESTAMP DEFAULT NOW()
);

-- Third-party vendors / service providers
CREATE TABLE IF NOT EXISTS gov.vendors (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name              VARCHAR(255) NOT NULL UNIQUE,
    vendor_type       VARCHAR(50),
                      -- MSP, SAAS, HARDWARE, INTEGRATOR, CLOUD
    criticality_score INTEGER DEFAULT 50,
    business_value_inr DECIMAL(15,2) DEFAULT 0,
    sector            VARCHAR(50),
    region            VARCHAR(50),
    assessment_score  DECIMAL(5,4) DEFAULT 0,
                      -- 0.0000 to 1.0000 (third-party assessment)
    last_assessed_at  TIMESTAMP,
    created_at        TIMESTAMP DEFAULT NOW()
);

-- Vendor → asset service map (TPRM cascade edges)
CREATE TABLE IF NOT EXISTS gov.asset_vendors (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id     UUID NOT NULL REFERENCES asset.assets(id) ON DELETE CASCADE,
    vendor_id    UUID NOT NULL REFERENCES gov.vendors(id) ON DELETE CASCADE,
    service_type VARCHAR(50),
    risk_share   DECIMAL(5,4) DEFAULT 1.0,
                 -- portion of asset risk attributable to this vendor
    created_at   TIMESTAMP DEFAULT NOW(),
    UNIQUE(asset_id, vendor_id)
);

-- ─── Governance dimensions on assets ─────────────────────────
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS sector VARCHAR(50);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS region VARCHAR(50);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS agency_id UUID;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS is_critical_infra BOOLEAN DEFAULT false;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS classification VARCHAR(20) DEFAULT 'CONFIDENTIAL';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_assets_sector_region ON asset.assets(sector, region);
CREATE INDEX IF NOT EXISTS idx_assets_agency ON asset.assets(agency_id);
CREATE INDEX IF NOT EXISTS idx_assets_critical_infra ON asset.assets(is_critical_infra)
    WHERE is_critical_infra = true;

CREATE INDEX IF NOT EXISTS idx_vendors_sector ON gov.vendors(sector);
CREATE INDEX IF NOT EXISTS idx_asset_vendors_vendor ON gov.asset_vendors(vendor_id);
CREATE INDEX IF NOT EXISTS idx_exercises_sector ON gov.exercises(sector);
CREATE INDEX IF NOT EXISTS idx_warnings_type ON gov.early_warnings(warning_type);


-- ======================================================================
-- MIGRATION · 009_create_data_sources.sql
-- ======================================================================

-- Migration 009: Registered ingestion data sources
-- Tracks the 7 production connectors feeding the observatory (scanners,
-- EDR, SIEM, web-edge logs, file-based batches) plus their health state.

CREATE TABLE IF NOT EXISTS public.data_sources (
    source_key        VARCHAR(50) PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    connector_type    VARCHAR(50) NOT NULL,
                      -- SCANNER, EDR, SIEM, WEB, FILE
    status            VARCHAR(20) NOT NULL DEFAULT 'CONFIGURED',
                      -- CONFIGURED, ACTIVE, CONNECTED, STANDBY, FAILED
    description       TEXT,
    last_ingested_at  TIMESTAMP,
    records_ingested  INTEGER DEFAULT 0,
    error_count       INTEGER DEFAULT 0,
    created_at        TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_data_sources_status ON public.data_sources(status);


-- ======================================================================
-- MIGRATION · 010_create_python_features.sql
-- ======================================================================

-- Migration 010: Refresh-token rotation, normalized event ledger, and the
-- RAG compliance corpus (pgvector embeddings stored as JSONB for portability).

-- ─── Refresh-token rotation ledger ───────────────────────────
CREATE TABLE IF NOT EXISTS auth.refresh_tokens (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(128) NOT NULL UNIQUE,
    family_id   UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMP NOT NULL,
    revoked_at  TIMESTAMP,
    replaced_by UUID
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON auth.refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family ON auth.refresh_tokens(family_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_revoked ON auth.refresh_tokens(revoked_at)
    WHERE revoked_at IS NULL;

-- ─── Normalized ingestion event ledger ───────────────────────
CREATE TABLE IF NOT EXISTS public.security_events (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type   VARCHAR(50) NOT NULL,
    source_asset UUID,
    source       VARCHAR(50) NOT NULL,
    details      TEXT,
    timestamp    TIMESTAMP NOT NULL DEFAULT NOW(),
    processed    BOOLEAN NOT NULL DEFAULT false,
    created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_security_events_type ON public.security_events(event_type);
CREATE INDEX IF NOT EXISTS idx_security_events_asset ON public.security_events(source_asset);
CREATE INDEX IF NOT EXISTS idx_security_events_ts ON public.security_events(timestamp DESC);

-- ─── RAG compliance corpus ───────────────────────────────────
-- embeddings are stored as JSONB for portability; try to enable pgvector
-- where available but never let its absence abort the migration.
DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS vector;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pgvector extension unavailable; embeddings retained as JSONB';
END $$;

CREATE TABLE IF NOT EXISTS gov.compliance_docs (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    framework   VARCHAR(50) NOT NULL,
    category    VARCHAR(100),
    title       VARCHAR(255) NOT NULL,
    content     TEXT NOT NULL,
    reference   VARCHAR(255),
    embedding   JSONB,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_compliance_docs_framework ON gov.compliance_docs(framework);


-- ======================================================================
-- MIGRATION · 011_create_threat_intel.sql
-- ======================================================================

-- Threat-intel feed snapshot cache (WS4).
-- Enrichment records pulled from CISA KEV, FIRST EPSS and NVD.
-- Kept in Postgres so the platform degrades gracefully offline.
CREATE TABLE IF NOT EXISTS public.threat_intel (
    id          SERIAL PRIMARY KEY,
    feed        VARCHAR(32) NOT NULL,
    cve_id      VARCHAR(32) NOT NULL,
    source_key  VARCHAR(64),
    payload     JSONB,
    fetched_at  TIMESTAMP   DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_threat_intel_feed_cve ON public.threat_intel (feed, cve_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_threat_intel_feed_cve ON public.threat_intel (feed, cve_id);


-- ======================================================================
-- MIGRATION · 012_create_alert_system.sql
-- ======================================================================

-- Alert rule engine + alert event ledger (WS8).
-- Threshold rules evaluated against risk metrics; fired alerts are persisted
-- and broadcast on the /topic/risk/alert STOMP topic for the live feed.
CREATE TABLE IF NOT EXISTS public.alert_rules (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(120) NOT NULL,
    metric          VARCHAR(32)  NOT NULL,   -- risk_score | total_eal | open_vulns | kev_count
    operator        VARCHAR(4)   DEFAULT '>=',
    threshold       NUMERIC(14, 2) NOT NULL,
    asset_id        UUID,
    severity        VARCHAR(16)  DEFAULT 'HIGH',  -- INFO | LOW | MEDIUM | HIGH | CRITICAL
    enabled         BOOLEAN      DEFAULT TRUE,
    created_at      TIMESTAMP    DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.alert_events (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_id     UUID REFERENCES public.alert_rules(id) ON DELETE SET NULL,
    metric      VARCHAR(32) NOT NULL,
    observed    NUMERIC(14, 2) NOT NULL,
    threshold   NUMERIC(14, 2) NOT NULL,
    severity    VARCHAR(16) NOT NULL,
    asset_id    UUID,
    payload     JSONB,
    fired_at    TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alert_events_fired ON public.alert_events (fired_at DESC);
CREATE INDEX IF NOT EXISTS idx_alert_rules_enabled ON public.alert_rules (enabled);

-- Sensible zero-configuration defaults for a fresh deployment (idempotent).
INSERT INTO public.alert_rules (name, metric, threshold, severity)
SELECT 'Enterprise risk score breach', 'risk_score', 75, 'HIGH'
WHERE NOT EXISTS (SELECT 1 FROM public.alert_rules WHERE metric = 'risk_score');

INSERT INTO public.alert_rules (name, metric, threshold, severity)
SELECT 'Annualised loss breach', 'total_eal', 10000000.00, 'CRITICAL'
WHERE NOT EXISTS (SELECT 1 FROM public.alert_rules WHERE metric = 'total_eal');

INSERT INTO public.alert_rules (name, metric, threshold, severity)
SELECT 'Open critical/high flood', 'open_vulns', 25, 'MEDIUM'
WHERE NOT EXISTS (SELECT 1 FROM public.alert_rules WHERE metric = 'open_vulns');

INSERT INTO public.alert_rules (name, metric, threshold, severity)
SELECT 'Known-exploited-vuln spike', 'kev_count', 5, 'CRITICAL'
WHERE NOT EXISTS (SELECT 1 FROM public.alert_rules WHERE metric = 'kev_count');


-- ======================================================================
-- PART 2 · SEED DATA (mirrors database/migrate_and_seed.py)
-- ======================================================================

INSERT INTO asset.assets (
    id, name, asset_type, environment, owner, department, ip_address,
    operating_system, business_value_inr, replacement_cost_inr,
    internet_exposed, criticality_score, data_sensitivity, annual_revenue_impact
) VALUES
    ('00000001-0001-0001-0001-000000000001','Payment Gateway Server','SERVER','PRODUCTION','Payments Team','Finance','10.0.1.10','Ubuntu 22.04 LTS',25000000,8000000,TRUE,95,'RESTRICTED',50000000),
    ('00000001-0001-0001-0001-000000000002','Customer Database','DATABASE','PRODUCTION','Data Engineering','Engineering','10.0.2.20','PostgreSQL 15 on RHEL 8',20000000,5000000,FALSE,90,'RESTRICTED',40000000),
    ('00000001-0001-0001-0001-000000000003','Identity Provider (SSO)','APPLICATION','PRODUCTION','Security Team','Security','10.0.3.30','Okta Cloud',15000000,3000000,TRUE,85,'CONFIDENTIAL',30000000),
    ('00000001-0001-0001-0001-000000000004','Customer Web Portal','APPLICATION','PRODUCTION','Frontend Team','Engineering','10.0.4.40','Node.js 20 on Ubuntu 22.04',18000000,4000000,TRUE,88,'CONFIDENTIAL',35000000),
    ('00000001-0001-0001-0001-000000000005','API Gateway','NETWORK','PRODUCTION','Platform Team','Engineering','10.0.5.50','Kong on Kubernetes',12000000,2000000,TRUE,82,'INTERNAL',25000000),
    ('00000001-0001-0001-0001-000000000006','Email Server','SERVER','PRODUCTION','IT Operations','IT','10.0.6.60','Exchange Online',8000000,1500000,TRUE,75,'CONFIDENTIAL',15000000),
    ('00000001-0001-0001-0001-000000000007','Backup & Recovery System','SERVER','PRODUCTION','IT Operations','IT','10.0.7.70','Veeam on Windows Server 2022',10000000,3000000,FALSE,70,'CONFIDENTIAL',20000000),
    ('00000001-0001-0001-0001-000000000008','Cloud Management Console','CLOUD','PRODUCTION','Cloud Engineering','Engineering',NULL,'AWS Console',22000000,1000000,TRUE,92,'RESTRICTED',45000000),
    ('00000001-0001-0001-0001-000000000009','SIEM Platform','APPLICATION','PRODUCTION','SOC Team','Security','10.0.9.90','Splunk Enterprise',14000000,5000000,FALSE,80,'CONFIDENTIAL',22000000),
    ('00000001-0001-0001-0001-000000000010','Development Environment','SERVER','DEVELOPMENT','DevOps Team','Engineering','10.1.0.10','Docker on Ubuntu 22.04',3000000,500000,FALSE,40,'INTERNAL',5000000),
    ('00000001-0001-0001-0001-000000000011','Analytics Data Warehouse','DATABASE','PRODUCTION','Data Engineering','Data','10.0.10.100','Snowflake',16000000,4000000,FALSE,72,'CONFIDENTIAL',18000000),
    ('00000001-0001-0001-0001-000000000012','VPN Concentrator','NETWORK','PRODUCTION','Network Team','IT','10.0.11.110','Fortinet FortiGate',7000000,2000000,TRUE,78,'CONFIDENTIAL',12000000);

INSERT INTO control.security_controls (
    id, name, control_type, description, implementation_cost_inr,
    annual_maintenance_inr, max_risk_reduction, implementation_time_days
) VALUES
    ('00000002-0001-0001-0001-000000000001','MFA - Administrative Accounts','MFA','Multi-factor authentication enforced for all administrative and privileged accounts.',200000,50000,0.25,14),
    ('00000002-0001-0001-0001-000000000002','MFA - All Employees','MFA','MFA enforced for all employee accounts across all systems.',500000,100000,0.3,30),
    ('00000002-0001-0001-0001-000000000003','EDR - Workstations','EDR','Endpoint Detection & Response deployed on all employee workstations.',800000,200000,0.2,21),
    ('00000002-0001-0001-0001-000000000004','EDR - Servers','EDR','EDR deployed on all production servers.',1200000,300000,0.22,21),
    ('00000002-0001-0001-0001-000000000005','Critical Patch Management','PATCH','Automated patching for critical and high-severity vulnerabilities within 48 hours.',300000,80000,0.35,14),
    ('00000002-0001-0001-0001-000000000006','Network Segmentation','SEGMENTATION','Micro-segmentation of production network with zero-trust policies.',1500000,200000,0.25,60),
    ('00000002-0001-0001-0001-000000000007','Backup Encryption & Immutability','BACKUP','Encrypted, immutable backups with 3-2-1 strategy and regular restore testing.',400000,100000,0.15,21),
    ('00000002-0001-0001-0001-000000000008','Web Application Firewall','FIREWALL','WAF deployed in front of all public-facing web applications.',600000,150000,0.18,14),
    ('00000002-0001-0001-0001-000000000009','SIEM Enhancement','SIEM','Enhanced SIEM with custom detection rules, 24/7 monitoring, and automated alerts.',1000000,250000,0.12,30),
    ('00000002-0001-0001-0001-000000000010','DLP - Email & Cloud Storage','DLP','Data Loss Prevention for email and cloud storage to prevent data exfiltration.',700000,180000,0.1,30);

INSERT INTO vuln.vulnerabilities (
    cve_id, cwe_id, title, description, cvss_score, severity,
    exploitability, affected_asset, internet_exposed, status, remediation, source
) VALUES
    ('CVE-2026-1001','CWE-89','SQL Injection in Payment API Endpoint','A critical SQL injection vulnerability was discovered in the payment processing API, allowing unauthenticated attackers to execute arbitrary SQL queries.',9.8,'CRITICAL',9.5,'00000001-0001-0001-0001-000000000001',TRUE,'OPEN','Apply parameterized queries to all database interactions. Deploy WAF rules as interim mitigation.','SCANNER'),
    ('CVE-2026-1002','CWE-798','Hardcoded Credentials in Cloud Management CLI','The cloud management CLI tool contains hardcoded AWS access keys in the source code repository.',9.1,'CRITICAL',9.0,'00000001-0001-0001-0001-000000000008',TRUE,'OPEN','Rotate all exposed credentials immediately. Implement secrets management (AWS Secrets Manager).','PENTEST'),
    ('CVE-2026-1003','CWE-22','Path Traversal in Customer Portal File Upload','The customer web portal allows arbitrary file read through path traversal in the file upload handler.',8.6,'CRITICAL',8.5,'00000001-0001-0001-0001-000000000004',TRUE,'OPEN','Sanitize file paths. Implement allowlist-based file access controls.','SCANNER'),
    ('CVE-2026-1004','CWE-611','XML External Entity (XXE) in API Gateway','The API gateway parses untrusted XML input without disabling external entity resolution.',8.2,'CRITICAL',8.0,'00000001-0001-0001-0001-000000000005',TRUE,'OPEN','Disable DTD processing and external entity resolution in XML parser.','SCANNER'),
    ('CVE-2026-1005','CWE-502','Deserialization of Untrusted Data in SIEM Collector','The SIEM log collector deserializes data from network sources without validation.',8.0,'CRITICAL',7.5,'00000001-0001-0001-0001-000000000009',FALSE,'OPEN','Implement input validation and use safe serialization libraries.','SCANNER'),
    ('CVE-2026-1006','CWE-287','Missing MFA on Identity Provider Admin Console','The IdP administrative console does not enforce multi-factor authentication for administrative users.',7.8,'HIGH',7.5,'00000001-0001-0001-0001-000000000003',TRUE,'OPEN','Enable mandatory MFA for all administrative accounts.','MANUAL'),
    ('CVE-2026-1007','CWE-311','Missing Encryption on Database Backups','Customer database backups are stored without encryption at rest.',7.5,'HIGH',6.0,'00000001-0001-0001-0001-000000000007',FALSE,'OPEN','Enable AES-256 encryption for all backup volumes.','MANUAL'),
    ('CVE-2026-1008','CWE-326','Weak TLS Configuration on VPN','VPN concentrator accepts TLS 1.0 and 1.1 connections, which are deprecated.',7.2,'HIGH',7.0,'00000001-0001-0001-0001-000000000012',TRUE,'OPEN','Disable TLS 1.0/1.1. Enforce TLS 1.3 minimum.','SCANNER'),
    ('CVE-2026-1009','CWE-918','Server-Side Request Forgery in Analytics Dashboard','The analytics dashboard fetches external URLs without validation, enabling SSRF attacks.',7.0,'HIGH',6.5,'00000001-0001-0001-0001-000000000011',FALSE,'OPEN','Implement URL allowlisting and block internal IP ranges.','SCANNER'),
    ('CVE-2026-1010','CWE-269','Privilege Escalation via Email Server','Regular users can access admin endpoints on the email server due to missing authorization checks.',6.8,'HIGH',6.0,'00000001-0001-0001-0001-000000000006',TRUE,'IN_PROGRESS','Implement role-based access control on all admin endpoints.','PENTEST'),
    ('CVE-2026-1011','CWE-770','Unrestricted File Upload in Customer Portal','No file type or size restrictions on customer portal upload feature.',6.5,'HIGH',6.0,'00000001-0001-0001-0001-000000000004',TRUE,'OPEN','Implement file type validation, size limits, and virus scanning.','SCANNER'),
    ('CVE-2026-1012','CWE-330','Insufficient Entropy in Session Tokens','Session tokens are generated using a predictable PRNG.',6.2,'MEDIUM',5.5,'00000001-0001-0001-0001-000000000004',TRUE,'OPEN','Use cryptographically secure random number generator for session tokens.','SCANNER'),
    ('CVE-2026-1013','CWE-532','Sensitive Information in Log Files','Payment processing logs contain PII and card data in plaintext.',5.5,'MEDIUM',4.0,'00000001-0001-0001-0001-000000000001',FALSE,'IN_PROGRESS','Implement log scrubbing to remove PII. Use structured logging with redaction.','SCANNER'),
    ('CVE-2026-1014','CWE-200','Information Disclosure via Error Messages','Verbose error messages expose internal stack traces and configuration details.',5.3,'MEDIUM',5.0,'00000001-0001-0001-0001-000000000005',TRUE,'OPEN','Implement generic error responses in production mode.','SCANNER'),
    ('CVE-2026-1015','CWE-759','No Salt in Password Hashing','Legacy authentication module uses MD5 without salt for password hashing.',5.0,'MEDIUM',4.5,'00000001-0001-0001-0001-000000000003',FALSE,'OPEN','Migrate to bcrypt/Argon2 with per-user salts.','MANUAL');

INSERT INTO control.asset_controls (
    asset_id, control_id, status, coverage_score, effectiveness_score, maturity_level
) VALUES
    ('00000001-0001-0001-0001-000000000003','00000002-0001-0001-0001-000000000001','ACTIVE',0.85,0.9,3),
    ('00000001-0001-0001-0001-000000000001','00000002-0001-0001-0001-000000000005','ACTIVE',0.7,0.8,2),
    ('00000001-0001-0001-0001-000000000004','00000002-0001-0001-0001-000000000008','ACTIVE',0.75,0.85,3),
    ('00000001-0001-0001-0001-000000000004','00000002-0001-0001-0001-000000000003','PLANNED',0.0,0.0,0),
    ('00000001-0001-0001-0001-000000000008','00000002-0001-0001-0001-000000000004','ACTIVE',0.6,0.7,2),
    ('00000001-0001-0001-0001-000000000002','00000002-0001-0001-0001-000000000007','ACTIVE',0.8,0.85,3),
    ('00000001-0001-0001-0001-000000000005','00000002-0001-0001-0001-000000000008','ACTIVE',0.9,0.95,3),
    ('00000001-0001-0001-0001-000000000006','00000002-0001-0001-0001-000000000001','PLANNED',0.0,0.0,0),
    ('00000001-0001-0001-0001-000000000006','00000002-0001-0001-0001-000000000010','PLANNED',0.0,0.0,0),
    ('00000001-0001-0001-0001-000000000009','00000002-0001-0001-0001-000000000009','ACTIVE',0.7,0.75,2),
    ('00000001-0001-0001-0001-000000000007','00000002-0001-0001-0001-000000000007','ACTIVE',0.85,0.9,3),
    ('00000001-0001-0001-0001-000000000012','00000002-0001-0001-0001-000000000006','ACTIVE',0.65,0.7,2),
    ('00000001-0001-0001-0001-000000000010','00000002-0001-0001-0001-000000000005','PLANNED',0.0,0.0,0),
    ('00000001-0001-0001-0001-000000000011','00000002-0001-0001-0001-000000000010','PLANNED',0.0,0.0,0);

INSERT INTO asset.asset_dependencies (
    asset_id, depends_on_id, dependency_type, criticality
) VALUES
    ('00000001-0001-0001-0001-000000000005','00000001-0001-0001-0001-000000000003','AUTH',90),
    ('00000001-0001-0001-0001-000000000005','00000001-0001-0001-0001-000000000002','DATA',80),
    ('00000001-0001-0001-0001-000000000004','00000001-0001-0001-0001-000000000005','NETWORK',85),
    ('00000001-0001-0001-0001-000000000004','00000001-0001-0001-0001-000000000003','AUTH',90),
    ('00000001-0001-0001-0001-000000000001','00000001-0001-0001-0001-000000000002','DATA',95),
    ('00000001-0001-0001-0001-000000000001','00000001-0001-0001-0001-000000000003','AUTH',88),
    ('00000001-0001-0001-0001-000000000001','00000001-0001-0001-0001-000000000005','NETWORK',80),
    ('00000001-0001-0001-0001-000000000002','00000001-0001-0001-0001-000000000007','INFRASTRUCTURE',75),
    ('00000001-0001-0001-0001-000000000006','00000001-0001-0001-0001-000000000003','AUTH',70),
    ('00000001-0001-0001-0001-000000000008','00000001-0001-0001-0001-000000000003','AUTH',85),
    ('00000001-0001-0001-0001-000000000008','00000001-0001-0001-0001-000000000009','MONITORING',60),
    ('00000001-0001-0001-0001-000000000011','00000001-0001-0001-0001-000000000002','DATA',85),
    ('00000001-0001-0001-0001-000000000011','00000001-0001-0001-0001-000000000007','INFRASTRUCTURE',60),
    ('00000001-0001-0001-0001-000000000009','00000001-0001-0001-0001-000000000005','LOG_SOURCE',55),
    ('00000001-0001-0001-0001-000000000009','00000001-0001-0001-0001-000000000001','LOG_SOURCE',55),
    ('00000001-0001-0001-0001-000000000009','00000001-0001-0001-0001-000000000004','LOG_SOURCE',55),
    ('00000001-0001-0001-0001-000000000007','00000001-0001-0001-0001-000000000008','INFRASTRUCTURE',65),
    ('00000001-0001-0001-0001-000000000012','00000001-0001-0001-0001-000000000003','AUTH',80);

INSERT INTO risk.risk_calculations (
    asset_id, risk_score, probability, financial_impact_inr,
    expected_annual_loss, risk_category, risk_factors,
    control_reduction, residual_risk
) VALUES
    ('00000001-0001-0001-0001-000000000001',48.22,0.3539,7362602.17,2605939.14,'MEDIUM','{"vulnCount": 2, "criticality": 95}',0.155,1824157.4),
    ('00000001-0001-0001-0001-000000000002',44.12,0.0723,10702592.74,774023.0,'MEDIUM','{"vulnCount": 0, "criticality": 90}',0.2353,541816.1),
    ('00000001-0001-0001-0001-000000000003',46.38,0.3792,4268388.05,1618649.39,'MEDIUM','{"vulnCount": 2, "criticality": 85}',0.1844,1133054.58),
    ('00000001-0001-0001-0001-000000000004',50.45,0.413,6137290.21,2534576.4,'HIGH','{"vulnCount": 3, "criticality": 88}',0.2011,1774203.48),
    ('00000001-0001-0001-0001-000000000005',43.1,0.2927,3734624.99,1092951.44,'MEDIUM','{"vulnCount": 2, "criticality": 82}',0.23,765066.01),
    ('00000001-0001-0001-0001-000000000006',37.92,0.2245,2329057.49,522859.78,'MEDIUM','{"vulnCount": 1, "criticality": 75}',0.2179,366001.84),
    ('00000001-0001-0001-0001-000000000007',34.95,0.2509,2118196.53,531546.69,'MEDIUM','{"vulnCount": 1, "criticality": 70}',0.2612,372082.68),
    ('00000001-0001-0001-0001-000000000008',46.63,0.2398,8826668.18,2116758.07,'MEDIUM','{"vulnCount": 1, "criticality": 92}',0.1311,1481730.65),
    ('00000001-0001-0001-0001-000000000009',42.8,0.2657,4867943.56,1293516.33,'MEDIUM','{"vulnCount": 1, "criticality": 80}',0.1185,905461.43),
    ('00000001-0001-0001-0001-000000000010',21.33,0.0597,766797.3,45756.05,'LOW','{"vulnCount": 0, "criticality": 40}',0.2207,32029.24),
    ('00000001-0001-0001-0001-000000000011',42.94,0.2507,6818604.07,1709511.51,'MEDIUM','{"vulnCount": 1, "criticality": 72}',0.2072,1196658.05),
    ('00000001-0001-0001-0001-000000000012',42.52,0.2673,2464719.08,658847.94,'MEDIUM','{"vulnCount": 1, "criticality": 78}',0.2104,461193.56);

INSERT INTO risk.risk_snapshots (
    risk_score, expected_annual_loss, total_controls_active,
    total_vulns_open, snapshot_date
) VALUES
    (44.18,16807350.34,17,16,CURRENT_DATE - 168),
    (44.08,16753083.07,16,16,CURRENT_DATE - 161),
    (43.98,16698815.79,16,16,CURRENT_DATE - 154),
    (43.88,16644548.52,15,16,CURRENT_DATE - 147),
    (43.78,16590281.24,15,16,CURRENT_DATE - 140),
    (43.68,16536013.97,14,16,CURRENT_DATE - 133),
    (43.58,16481746.69,14,16,CURRENT_DATE - 126),
    (43.48,16427479.42,13,16,CURRENT_DATE - 119),
    (43.38,16373212.14,13,16,CURRENT_DATE - 112),
    (43.28,16318944.87,12,16,CURRENT_DATE - 105),
    (43.18,16264677.59,12,16,CURRENT_DATE - 98),
    (43.08,16210410.32,11,15,CURRENT_DATE - 91),
    (42.98,16156143.04,11,15,CURRENT_DATE - 84),
    (42.88,16101875.77,10,15,CURRENT_DATE - 77),
    (42.78,16047608.49,10,15,CURRENT_DATE - 70),
    (42.68,15993341.22,9,15,CURRENT_DATE - 63),
    (42.58,15939073.94,9,15,CURRENT_DATE - 56),
    (42.48,15884806.67,8,15,CURRENT_DATE - 49),
    (42.38,15830539.39,8,15,CURRENT_DATE - 42),
    (42.28,15776272.12,7,15,CURRENT_DATE - 35),
    (42.18,15722004.84,7,15,CURRENT_DATE - 28),
    (42.08,15667737.57,6,15,CURRENT_DATE - 21),
    (41.98,15613470.29,6,15,CURRENT_DATE - 14),
    (41.88,15559203.02,5,15,CURRENT_DATE - 7),
    (41.78,15504935.74,5,15,CURRENT_DATE - 0);

INSERT INTO gov.agencies (id, name, agency_type, sector, region, classification)
VALUES ('00000004-0001-0001-0001-000000000001', 'National Payments Corp', 'PSU', 'BANKING', 'WEST', 'RESTRICTED')
ON CONFLICT (id) DO NOTHING;

UPDATE gov.agencies
SET agency_type = 'PSU', sector = 'BANKING',
    region = 'WEST', classification = 'RESTRICTED'
WHERE id = '00000004-0001-0001-0001-000000000001';

INSERT INTO gov.agencies (id, name, agency_type, sector, region, classification)
VALUES ('00000004-0001-0001-0001-000000000002', 'Telecom Infrastructure Ministry', 'GOVT', 'TELECOM', 'NORTH', 'CONFIDENTIAL')
ON CONFLICT (id) DO NOTHING;

UPDATE gov.agencies
SET agency_type = 'GOVT', sector = 'TELECOM',
    region = 'NORTH', classification = 'CONFIDENTIAL'
WHERE id = '00000004-0001-0001-0001-000000000002';

INSERT INTO gov.agencies (id, name, agency_type, sector, region, classification)
VALUES ('00000004-0001-0001-0001-000000000003', 'Digital Health Authority', 'GOVT', 'HEALTH', 'SOUTH', 'CONFIDENTIAL')
ON CONFLICT (id) DO NOTHING;

UPDATE gov.agencies
SET agency_type = 'GOVT', sector = 'HEALTH',
    region = 'SOUTH', classification = 'CONFIDENTIAL'
WHERE id = '00000004-0001-0001-0001-000000000003';

INSERT INTO gov.sector_profiles (sector, sector_name, regulator, threshold_critical_mln, weight)
VALUES ('BANKING', 'Banking & Payments', 'RBI', 50.0, 1.2)
ON CONFLICT (sector) DO UPDATE SET
    sector_name = EXCLUDED.sector_name, regulator = EXCLUDED.regulator,
    threshold_critical_mln = EXCLUDED.threshold_critical_mln, weight = EXCLUDED.weight;

INSERT INTO gov.sector_profiles (sector, sector_name, regulator, threshold_critical_mln, weight)
VALUES ('TELECOM', 'Telecommunications & Networks', 'TRAI', 30.0, 1.0)
ON CONFLICT (sector) DO UPDATE SET
    sector_name = EXCLUDED.sector_name, regulator = EXCLUDED.regulator,
    threshold_critical_mln = EXCLUDED.threshold_critical_mln, weight = EXCLUDED.weight;

INSERT INTO gov.sector_profiles (sector, sector_name, regulator, threshold_critical_mln, weight)
VALUES ('HEALTH', 'Healthcare & Public Health', 'IRDAI + DPDP Act', 40.0, 1.1)
ON CONFLICT (sector) DO UPDATE SET
    sector_name = EXCLUDED.sector_name, regulator = EXCLUDED.regulator,
    threshold_critical_mln = EXCLUDED.threshold_critical_mln, weight = EXCLUDED.weight;

UPDATE asset.assets
SET sector = 'BANKING', region = 'WEST',
    agency_id = '00000004-0001-0001-0001-000000000001',
    is_critical_infra = TRUE, classification = 'RESTRICTED'
WHERE id = '00000001-0001-0001-0001-000000000001';

UPDATE asset.assets
SET sector = 'BANKING', region = 'WEST',
    agency_id = '00000004-0001-0001-0001-000000000001',
    is_critical_infra = TRUE, classification = 'RESTRICTED'
WHERE id = '00000001-0001-0001-0001-000000000002';

UPDATE asset.assets
SET sector = 'BANKING', region = 'WEST',
    agency_id = '00000004-0001-0001-0001-000000000001',
    is_critical_infra = TRUE, classification = 'CONFIDENTIAL'
WHERE id = '00000001-0001-0001-0001-000000000003';

UPDATE asset.assets
SET sector = 'BANKING', region = 'WEST',
    agency_id = '00000004-0001-0001-0001-000000000001',
    is_critical_infra = TRUE, classification = 'CONFIDENTIAL'
WHERE id = '00000001-0001-0001-0001-000000000004';

UPDATE asset.assets
SET sector = 'BANKING', region = 'WEST',
    agency_id = '00000004-0001-0001-0001-000000000001',
    is_critical_infra = TRUE, classification = 'CONFIDENTIAL'
WHERE id = '00000001-0001-0001-0001-000000000005';

UPDATE asset.assets
SET sector = 'BANKING', region = 'CENTRAL',
    agency_id = '00000004-0001-0001-0001-000000000001',
    is_critical_infra = TRUE, classification = 'RESTRICTED'
WHERE id = '00000001-0001-0001-0001-000000000008';

UPDATE asset.assets
SET sector = 'TELECOM', region = 'NORTH',
    agency_id = '00000004-0001-0001-0001-000000000002',
    is_critical_infra = FALSE, classification = 'CONFIDENTIAL'
WHERE id = '00000001-0001-0001-0001-000000000006';

UPDATE asset.assets
SET sector = 'TELECOM', region = 'NORTH',
    agency_id = '00000004-0001-0001-0001-000000000002',
    is_critical_infra = FALSE, classification = 'CONFIDENTIAL'
WHERE id = '00000001-0001-0001-0001-000000000012';

UPDATE asset.assets
SET sector = 'HEALTH', region = 'SOUTH',
    agency_id = '00000004-0001-0001-0001-000000000003',
    is_critical_infra = TRUE, classification = 'RESTRICTED'
WHERE id = '00000001-0001-0001-0001-000000000009';

UPDATE asset.assets
SET sector = 'HEALTH', region = 'SOUTH',
    agency_id = '00000004-0001-0001-0001-000000000003',
    is_critical_infra = TRUE, classification = 'CONFIDENTIAL'
WHERE id = '00000001-0001-0001-0001-000000000007';

UPDATE asset.assets
SET sector = 'HEALTH', region = 'SOUTH',
    agency_id = '00000004-0001-0001-0001-000000000003',
    is_critical_infra = FALSE, classification = 'INTERNAL'
WHERE id = '00000001-0001-0001-0001-000000000010';

UPDATE asset.assets
SET sector = 'HEALTH', region = 'EAST',
    agency_id = '00000004-0001-0001-0001-000000000003',
    is_critical_infra = TRUE, classification = 'RESTRICTED'
WHERE id = '00000001-0001-0001-0001-000000000011';

INSERT INTO gov.vendors (
    id, name, vendor_type, criticality_score, business_value_inr,
    sector, region, assessment_score, last_assessed_at
) VALUES ('00000003-0001-0001-0001-000000000001', 'CorePay Cloud Services', 'CLOUD', 90, 50000000, 'BANKING', 'WEST', 0.65, CURRENT_TIMESTAMP - INTERVAL '30 days')
ON CONFLICT (id) DO NOTHING;

UPDATE gov.vendors
SET vendor_type = 'CLOUD', criticality_score = 90,
    business_value_inr = 50000000, sector = 'BANKING',
    region = 'WEST', assessment_score = 0.65,
    last_assessed_at = CURRENT_TIMESTAMP - INTERVAL '30 days'
WHERE id = '00000003-0001-0001-0001-000000000001';

INSERT INTO gov.vendors (
    id, name, vendor_type, criticality_score, business_value_inr,
    sector, region, assessment_score, last_assessed_at
) VALUES ('00000003-0001-0001-0001-000000000002', 'NetSec Managed Security', 'MSP', 72, 20000000, 'TELECOM', 'NORTH', 0.55, CURRENT_TIMESTAMP - INTERVAL '30 days')
ON CONFLICT (id) DO NOTHING;

UPDATE gov.vendors
SET vendor_type = 'MSP', criticality_score = 72,
    business_value_inr = 20000000, sector = 'TELECOM',
    region = 'NORTH', assessment_score = 0.55,
    last_assessed_at = CURRENT_TIMESTAMP - INTERVAL '30 days'
WHERE id = '00000003-0001-0001-0001-000000000002';

INSERT INTO gov.vendors (
    id, name, vendor_type, criticality_score, business_value_inr,
    sector, region, assessment_score, last_assessed_at
) VALUES ('00000003-0001-0001-0001-000000000003', 'MedLens Data Processor', 'SAAS', 60, 15000000, 'HEALTH', 'SOUTH', 0.72, CURRENT_TIMESTAMP - INTERVAL '30 days')
ON CONFLICT (id) DO NOTHING;

UPDATE gov.vendors
SET vendor_type = 'SAAS', criticality_score = 60,
    business_value_inr = 15000000, sector = 'HEALTH',
    region = 'SOUTH', assessment_score = 0.72,
    last_assessed_at = CURRENT_TIMESTAMP - INTERVAL '30 days'
WHERE id = '00000003-0001-0001-0001-000000000003';

INSERT INTO gov.asset_vendors (asset_id, vendor_id, service_type, risk_share)
VALUES
    ('00000001-0001-0001-0001-000000000001','00000003-0001-0001-0001-000000000001','Payments platform',0.6),
    ('00000001-0001-0001-0001-000000000002','00000003-0001-0001-0001-000000000001','Data services',0.4),
    ('00000001-0001-0001-0001-000000000003','00000003-0001-0001-0001-000000000002','Identity monitoring',0.5),
    ('00000001-0001-0001-0001-000000000005','00000003-0001-0001-0001-000000000002','Perimeter defense',0.3),
    ('00000001-0001-0001-0001-000000000006','00000003-0001-0001-0001-000000000002','Email security',0.4),
    ('00000001-0001-0001-0001-000000000009','00000003-0001-0001-0001-000000000002','SIEM operations',0.3),
    ('00000001-0001-0001-0001-000000000011','00000003-0001-0001-0001-000000000003','Analytics aggregation',0.5),
    ('00000001-0001-0001-0001-000000000010','00000003-0001-0001-0001-000000000003','Dev tooling',0.3);

INSERT INTO gov.exercises (
    id, name, scenario_key, impact_scope, sector, region,
    baseline_eal, simulated_eal, eal_reduction, eal_reduction_percent, status
) VALUES ('00000005-0001-0001-0001-000000000001',
    'Drill — Ransomware Surge (Banking Sector)',
    'RANSOMWARE', 'SECTOR', 'BANKING', 'WEST',
    8626139.37, 11904072.33,
    3277932.96, 38.0,
    'COMPLETED');

INSERT INTO gov.early_warnings (
    warning_type, target_type, target_id, severity, title, description,
    threshold_value, current_value, status
) VALUES (
    'EAL_SPIKE', 'SECTOR', 'BANKING', 'HIGH',
    'Banking sector EAL trending past RBI critical threshold',
    'Aggregate banking-sector expected annual loss exceeds Rs. 5 Cr threshold. Recommended: prioritise payments-critical assets in the next budget cycle.',
    50000000.0, 8626139.37, 'OPEN');
INSERT INTO gov.early_warnings (
    warning_type, target_type, target_id, severity, title, description,
    threshold_value, current_value, status
) VALUES (
    'VENDOR_RISK', 'VENDOR', 'NetSec Managed Security', 'MEDIUM',
    'Third-party assessment below acceptance threshold',
    'NetSec assessment score (0.55) is below the 0.60 acceptance bar. Schedule reassessment and review privileged access the MSP holds.',
    0.60, 0.55, 'OPEN');

INSERT INTO public.data_sources (
    source_key, name, connector_type, status, description,
    last_ingested_at, records_ingested, error_count
) VALUES
    ('NESSUS','Tenable Nessus Scanner','SCANNER','CONNECTED','Vulnerability scans across 1,200+ hosts; 1,582 findings ingested this week.',CURRENT_TIMESTAMP - INTERVAL '2 hours',1421,0),
    ('CROWDSTRIKE','CrowdStrike Falcon EDR','EDR','CONNECTED','Endpoint detection and response telemetry for all production endpoints.',CURRENT_TIMESTAMP - INTERVAL '5 minutes',3248,1),
    ('DEFENDER_ENDPOINT','Microsoft Defender for Endpoint','EDR','ACTIVE','Endpoint signals fused into asset risk attribution for Windows estate.',CURRENT_TIMESTAMP - INTERVAL '12 minutes',1890,0),
    ('SPLUNK','Splunk SIEM','SIEM','CONNECTED','Correlated security events; 4-minute ingestion SLA for alert pivots.',CURRENT_TIMESTAMP - INTERVAL '4 minutes',15204,2),
    ('WAF_LOGS','WAF / CDN Edge Logs','WEB','CONNECTED','Web application firewall and CDN edge request logs (1h batches).',CURRENT_TIMESTAMP - INTERVAL '1 hour',88742,0),
    ('JSON_BATCH','Generic JSON Batch','FILE','CONFIGURED','Landing zone for vendor/regulator JSON payloads via ingestion API.',NULL,0,0),
    ('CSV_BATCH','Generic CSV Batch','FILE','CONFIGURED','Landing zone for flat-file asset/inventory exports.',NULL,0,0);


-- ======================================================================
-- PART 3 · VERIFICATION (run these after the setup to confirm)
-- ======================================================================

SELECT 'auth.users' AS table_name, COUNT(*) AS rows FROM auth.users
UNION ALL SELECT 'asset.assets', COUNT(*) FROM asset.assets
UNION ALL SELECT 'control.security_controls', COUNT(*) FROM control.security_controls
UNION ALL SELECT 'vuln.vulnerabilities', COUNT(*) FROM vuln.vulnerabilities
UNION ALL SELECT 'control.asset_controls', COUNT(*) FROM control.asset_controls
UNION ALL SELECT 'asset.asset_dependencies', COUNT(*) FROM asset.asset_dependencies
UNION ALL SELECT 'risk.risk_calculations', COUNT(*) FROM risk.risk_calculations
UNION ALL SELECT 'risk.risk_snapshots', COUNT(*) FROM risk.risk_snapshots
UNION ALL SELECT 'gov.agencies', COUNT(*) FROM gov.agencies
UNION ALL SELECT 'gov.sector_profiles', COUNT(*) FROM gov.sector_profiles
UNION ALL SELECT 'gov.vendors', COUNT(*) FROM gov.vendors
UNION ALL SELECT 'gov.asset_vendors', COUNT(*) FROM gov.asset_vendors
UNION ALL SELECT 'gov.exercises', COUNT(*) FROM gov.exercises
UNION ALL SELECT 'gov.early_warnings', COUNT(*) FROM gov.early_warnings
UNION ALL SELECT 'public.data_sources', COUNT(*) FROM public.data_sources
UNION ALL SELECT 'public.alert_rules', COUNT(*) FROM public.alert_rules
ORDER BY table_name;
