-- ============================================================================
-- CyberRisk Quantifier — NeonDB quickstart
-- ============================================================================
--
-- READ THIS FIRST: you probably do not need to run anything.
--
-- The backend creates and populates its own database. On every boot
-- deploy/render/start.sh runs `database/migrate_and_seed.py`, which applies
-- database/init.sql, then migrations 001-012, then the seed data. It is
-- idempotent, so it is safe on every deploy and it is how your Render
-- database gets built. You only need a connection string.
--
-- So the normal flow is:
--   1. Neon Console -> create a project (free) -> it gives you a database
--   2. Copy the POOLED connection string
--   3. Paste it into Render as DATABASE_URL when the Blueprint prompts
--   Done. The schema and seed appear by themselves on first deploy.
--
-- This file is for the cases where you want to do it by hand, or want to
-- inspect what should exist. Sections are ordered by how likely you are to
-- need them.
--
-- ---------------------------------------------------------------------------
-- 1. CREATE THE DATABASE
-- ---------------------------------------------------------------------------
-- Neon already creates a database named `neondb` when you create a project,
-- and the connection string Neon hands you points at it. That is the path to
-- take: nothing to do, and nothing to change in the connection string.
--
-- `CREATE DATABASE` only if you want a second, differently named database.
-- Run this while connected to an existing database (Neon Console -> SQL Editor
-- opens on `neondb` by default):
--
--   CREATE DATABASE cyberrisk;
--
-- If you do that, your connection string must end in `/cyberrisk` instead of
-- `/neondb`. Everything after this point is unchanged.
--
-- You cannot run CREATE DATABASE from inside a transaction block, and you
-- cannot drop the database you are currently connected to.

-- Uncomment to create an additional database:
-- CREATE DATABASE cyberrisk;

-- To see what already exists:
--   SELECT datname FROM pg_database WHERE datistemplate = false ORDER BY datname;


-- ---------------------------------------------------------------------------
-- 2. SCHEMAS  (applied automatically by migrate_and_seed.py — safe to re-run)
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS asset;
CREATE SCHEMA IF NOT EXISTS vuln;
CREATE SCHEMA IF NOT EXISTS control;
CREATE SCHEMA IF NOT EXISTS risk;
CREATE SCHEMA IF NOT EXISTS investment;
CREATE SCHEMA IF NOT EXISTS gov;


-- ---------------------------------------------------------------------------
-- 3. TABLES, INDEXES, FUNCTIONS AND SEED DATA
-- ---------------------------------------------------------------------------
-- Do NOT paste SQL from here by hand on an empty database unless you intend to
-- bypass the app's own migration path. Instead use one of:
--
--   (a) Automatic (recommended): deploy to Render. start.sh runs
--       database/migrate_and_seed.py, which applies database/init.sql,
--       all twelve migrations in database/migrations/, and the seed data.
--
--   (b) Manual full snapshot: run the entire contents of
--       database/neon_setup.sql (generated by database/generate_neon_setup.py).
--       That file is schema + migrations 001-012 + seed in one paste. It is
--       written for a ONE-TIME run on an empty database: schemas use
--       IF NOT EXISTS, but the core seed inserts are plain INSERTs, so
--       re-running it on a seeded database will fail on duplicate keys.
--
--   (c) Just the schema, no seed: run these in order —
--         database/init.sql
--         database/migrations/001_create_auth_tables.sql
--         database/migrations/002_create_asset_tables.sql
--         database/migrations/003_create_vuln_tables.sql
--         database/migrations/004_create_control_tables.sql
--         database/migrations/005_create_risk_tables.sql
--         database/migrations/006_create_investment_tables.sql
--         database/migrations/007_create_audit_tables.sql
--         database/migrations/008_create_sovereignty_tables.sql
--         database/migrations/009_create_data_sources.sql
--         database/migrations/010_create_python_features.sql
--         database/migrations/011_create_threat_intel.sql
--         database/migrations/012_create_alert_system.sql


-- ---------------------------------------------------------------------------
-- 4. VERIFY  (paste after deploying — everything should return rows)
-- ---------------------------------------------------------------------------

-- 4a. All seven schemas exist. Expect 7 rows.
SELECT nspname AS schema
FROM pg_namespace
WHERE nspname IN ('auth','asset','vuln','control','risk','investment','gov')
ORDER BY nspname;

-- 4b. Table count per schema. Expect a row for each of the seven above.
--     `public.data_sources` is created outside the named schemas by migration
--     009, so add a query for it too if you want a complete picture.
SELECT table_schema, COUNT(*) AS tables
FROM information_schema.tables
WHERE table_schema IN ('auth','asset','vuln','control','risk','investment','gov')
GROUP BY table_schema
ORDER BY table_schema;

-- 4c. Demo logins. Expect 3 rows, all with role CISO / ANALYST / ANALYST.
--     Password for all three: Scro@2026!
SELECT username, email, role, is_active FROM auth.users ORDER BY role DESC, username;

-- 4d. Seeded core data. Expect: assets 12, controls 10, vulnerabilities 15,
--     agencies 3, data sources 7.
SELECT 'assets'        AS entity, COUNT(*) FROM asset.assets
UNION ALL SELECT 'security_controls',  COUNT(*) FROM control.security_controls
UNION ALL SELECT 'vulnerabilities',    COUNT(*) FROM vuln.vulnerabilities
UNION ALL SELECT 'agencies',          COUNT(*) FROM gov.agencies
UNION ALL SELECT 'data_sources',      COUNT(*) FROM public.data_sources
ORDER BY entity;

-- 4e. Risk calculations were generated for every asset. Expect assets = risks.
SELECT (SELECT COUNT(*) FROM asset.assets)           AS assets,
       (SELECT COUNT(*) FROM risk.risk_calculations) AS risk_calculations,
       (SELECT COUNT(*) FROM risk.risk_snapshots)    AS snapshots;

-- 4f. The audit chain is intact: every row links to a previous one.
--     Expect broken_links = 0.
SELECT COUNT(*) AS broken_links
FROM risk.audit_entries AS c
WHERE c.prev_hash IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM risk.audit_entries p WHERE p.data_hash = c.prev_hash);


-- ---------------------------------------------------------------------------
-- 5. THINGS THAT COMMONLY GO WRONG
-- ---------------------------------------------------------------------------
--
-- "relation ... does not exist" from the app, but the tables are there
--   -> The connection string's search_path is not reaching your schemas. The
--      services always qualify names (auth.users, asset.assets), so this means
--      the app is pointed at a different database than the one you inspected.
--      Check the database name at the end of DATABASE_URL.
--
-- SSL / "server closed the connection unexpectedly"
--   -> Use the POOLED (-pooler) connection string, and keep
--      `?sslmode=require`. Neon requires TLS. start.sh appends sslmode=require
--      automatically if it is missing, and works with either the pooled or the
--      direct host.
--
-- "too many connections"
--   -> Neon caps connections per database. Keep DB_POOL_SIZE=2 and
--      DB_MAX_OVERFLOW=2 in render.yaml. Eight services share one database, so
--      the defaults of 10+20 would try to open ~240 connections.
--
-- Everything times out from Render
--   -> Neon free projects pause after a period of inactivity and resume on the
--      next connection, which can take a few seconds. start.sh already waits up
--      to ~5 minutes for Postgres before continuing, so a cold Neon simply
--      delays boot rather than failing the deploy.